---

- name: install epel-release repo
  yum:
    name: epel-release
    state: present
  become: yes
  become_user: root

- name: install multiscanner system dependencies
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - autoconf
    - automake
    - curl
    - gcc
    - libffi-devel
    - libtool
    - make
    - python-devel
    - python-pip
    - ssdeep-devel
    - tar
    - git
  become: yes
  become_user: root

- name: copy multiscanner source
  copy:
    src: "../../{{local_resource_prefix}}/multiscanner.tgz"
    dest: "{{ multiscanner_install_prefix }}"
  become: yes
  become_user: root

- name: unzip multiscanner source
  unarchive:
    src: "{{ multiscanner_install_prefix }}/multiscanner.tgz"
    dest: "{{ multiscanner_install_prefix }}"
    remote_src: yes
    creates: "{{ multiscanner_install_prefix }}/multiscanner"
    owner: "{{ ms_user }}"
    group: root
  become: yes
  become_user: root

- name: create multiscanner virtualenv directory and set permissions
  file: "path={{ multiscanner_venv }} state=directory mode=0700 owner={{ ms_user }} recurse=yes"
  become: yes
  become_user: root

- name: install multiscanner python dependencies
  pip:
    requirements: "{{ multiscanner_install_prefix }}/multiscanner/requirements3.txt"
    virtualenv: "{{ multiscanner_venv }}"
    virtualenv_python: "{{ python_install_prefix }}/bin/python"
    virtualenv_site_packages: yes
  become: yes
  become_user: "{{ ms_user }}"

# Copy configs
- name: copy multiscanner main config
  template: src=config.ini.j2 dest={{ multiscanner_install_prefix }}/multiscanner/config.ini mode=755 owner=multiscanner group=root
  register: restart_ms_svc
  become: yes
  become_user: root


- name: copy multiscanner api config
  template: src=api_config.ini.j2 dest={{ multiscanner_install_prefix }}/multiscanner/api_config.ini mode=755 owner=multiscanner group=root
  register: restart_ms_svc
  become: yes
  become_user: root


- name: copy multiscanner storage config
  template: src=storage.ini.j2 dest={{ multiscanner_install_prefix }}/multiscanner/storage.ini mode=755 owner=multiscanner group=root
  register: restart_ms_svc
  become: yes
  become_user: root
